---

- name: Configure Fedora 37 Workstation
  hosts: localhost
  connection: local
  become: yes
  tasks:

 - name: Ensure system is updated
   dnf:
     name: '*'
     state: latest

 - name: Install common packages
   dnf:
     name:
       - vim
       - nvim
       - git
       - htop
       - net-tools
       
   state: present

 - name: Install EPEL repository
   dnf:
     name: epel-release
     state: present

 - name: Start and enable firewalld
   systemd:
     name: firewalld
     state: started
     enabled: yes
